### ISSUE TITLE
'geojson-polygon-labels' for concave or with a hole features

### ISSUE THREAD

**Issue by spatialhast** [andrewharvey/geojson-polygon-labels#16]
I checked 'geojson-polygon-labels' tool for concave features and in all cases (polylabel,centroid,center-of-mass) I received points outside the polygon. Does it possibly generate points inside concave polygons with 'geojson-polygon-labels' tool?

eample generated points with 'polylabel (red), centroid (blue), center-of-mass (green)' options
![image](https://user-images.githubusercontent.com/3269617/64919268-1f8c9180-d7b1-11e9-8e59-bec87c916891.png)

**Comment by andrewharvey** [comment]
polylabel should result in the label being within the polygon, if this isn't the case, I suggest providing a sample GeoJSON where the results aren't as you expect and creating an issue in the upstream polylabel repo at https://github.com/mapbox/polylabel (feel free to CC me).

Centroid and center of mass aren't guaranteed to be within the polygon.

I'll close this out here because it looks like it's more of an upstream issue with polylabel.
