### ISSUE TITLE
--include-minzoom is always true

### ISSUE THREAD

**Issue by pjsier** [andrewharvey/geojson-polygon-labels#6]
Since the default for `--include-minzoom` is '0-16' rather than `false`, there's currently no way of turning off the inclusion of the `tippecanoe` property

**Comment by andrewharvey** [comment]
The intention was that if `--include-minzoom` is omitted then it won't add in the tippecanoe minzoom property, if `--include-minzoom` is included then it does using a default of 0-16, otherwise values are defined like `--include-minzoom=0-16`. I can't work out how to do that with yargs so I'll drop the default so you either include it with your own minzoom `min-max` value or omit the flag.

I've done a quick pass to try to fix this in master branch on github. Could you please try it out? I'll push it to a patch release after.

**Comment by pjsier** [comment]
Just tried it out locally, and that works for me! Omitting `--include-minzoom` doesn't add the tippecanoe property as expected, but including it with "0-16" sets it the same way it had before. Thanks for fixing this so quickly!
