### ISSUE TITLE
WIP: support for large files (> 256 MB)

### ISSUE THREAD

**Issue by jdar** [andrewharvey/geojson-polygon-labels#8]
I have started to extend this client. I am noting this here, in case it helps anyone else.

It is not unlikely that this client will be used with large sets of polygons.

github.com:jdar/geojson-polygon-labels.git

It does not put out valid json (I can't figure out how to stream to array, rather than object), but it is good enough for me (I'm just correcting the json with sed).

**Comment by andrewharvey** [comment]
Thanks for sharing.

The current code should support input files >256MB but may have issues with large output files. Since the output is points, this isn't something I've run into, but I think using geojson-stream like in https://github.com/andrewharvey/geojson-id-streaming/blob/master/index.js would be my preferred way of solving this here.

**Comment by jdar** [comment]
:ok_hand:

good tip. I'll look into geojson streaming if I need more oomph
